name: 'Python script execution'
description: 'Execute a given python script with its dependencies and show the output'
inputs:
  script:
    description: 'The python script with to execute'
    required: true
  args:
    description: 'The arguments to pass to the script'
    required: false
  python-version:
    description: 'The python version to use'
    required: false
  requirements:
    description: 'File path or list of Python package requirements'
    required: true
  constraints:
    description: 'File path or list of Python package constraints'
    required: false
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
    - uses: actions/checkout@v2
    - name: Install Python packages
      run: |
         constraints="-c "
         if [ -n "${{ inputs.constraints }}" ]; then
          if [ -f "${{ inputs.constraints }}" ]; then
            constraints+="${{ inputs.constraints }}"
          else
            for file in ${{ inputs.constraints }}; do
              constraints+="$file "
            done
          fi
          fi
          if [ -n "${{ inputs.requirements }}" ]; then
            if [ -f "${{ inputs.requirements }}" ]; then
              pip install -r "${{ inputs.requirements }}" $constraints
            else
              for package in ${{ inputs.requirements }}; do
                pip install "$package" $constraints
              done
            fi
          fi
      shell: bash
    - name: Execute Python script
      run: |
        python ${{ inputs.script }} ${{ inputs.args }}
      shell: bash