name: 'Python script execution'
description: 'Execute a given python script with its dependencies and show the output'
inputs:
  script:
    description: 'The python script with to execute'
    required: true
  args:
    description: 'The arguments to pass to the script'
    required: false
  python-version:
    description: 'The python version to use'
    required: true
  requirements:
    description: 'File path or list of Python package requirements'
    required: false
  constraints:
    description: 'File path or list of Python package constraints'
    required: false
outputs: 
  output:
    description: 'The output of the script'
    value: ${{ steps.script-execution.outputs.OUTPUT }}
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
    - uses: actions/checkout@v3
    - name: Install Python packages
      run: |
         touch constraints.tmp
         if [ -n "${{ inputs.constraints }}" ]; then
          if [ -f "${{ inputs.constraints }}" ]; then
            cat ${{ inputs.constraints }} > constraints.tmp
          else
            for file in ${{ inputs.constraints }}; do
              echo $file >> constraints.tmp
            done
          fi
          fi
          if [ -n "${{ inputs.requirements }}" ]; then
            if [ -f "${{ inputs.requirements }}" ]; then
              pip install -r "${{ inputs.requirements }}" -c constraints.tmp
            else
              for package in ${{ inputs.requirements }}; do
                pip install "$package" -c constraints.tmp
              done
            fi
          fi
      shell: bash
    - name: Execute Python script
      id: script-execution
      run: echo "OUTPUT=$(python ${{ inputs.script }} ${{ inputs.args }})" >> $GITHUB_OUTPUT
      shell: bash
    - name: Print script output
      run: echo "${{ steps.script-execution.outputs.OUTPUT }}"
      shell: bash