name: Python Package Install and Script Execution
on:
  workflow_dispatch:
    inputs:
      python_version:
        description: 'Python version to use'
        required: true
      requirements:
        description: 'File path or list of Python package requirements'
        required: true
      constraints:
        description: 'File path or list of Python package constraints'
        required: false
      script:
        description: 'File path of the script to execute'
        required: true
      args:
        description: 'Arguments to pass to the script'
        required: false
jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Python Package Install and Script Execution composite action
        id: script-execution
        uses: Quentique/amd-devops-intern-composite-action@77ae6506d9549cbcb00c8d6bcefbfb0712689c69
        with:
          python-version: ${{ github.event.inputs.python_version }}
          requirements: ${{ github.event.inputs.requirements }}
          constraints: ${{ github.event.inputs.constraints }}
          script: ${{ github.event.inputs.script }}
          args: ${{ github.event.inputs.args }}
    outputs:
        script-output: ${{ steps.script-execution.outputs.output }}
